name: Prepare build environment
description: Ensures that everything is prepared for our build jobs

runs:
  using: "composite"
  steps:
    - name: Install emscripten toolchain
      shell: bash
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install 3.1.72
        ./emsdk activate 3.1.72
        source ./emsdk_env.sh
        # Export emsdk environment variables
        echo "PATH=$PATH" >> $GITHUB_ENV
        echo "EMSDK=$EMSDK" >> $GITHUB_ENV
        echo "EMSDK_NODE=$EMSDK_NODE" >> $GITHUB_ENV
